// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"crazyfarmbot/config"
	"crazyfarmbot/src/controller"
	"crazyfarmbot/src/services"
	"github.com/google/wire"
)

// Injectors from wire.go:

func Init() *Initialization {
	bot := config.GetBotInstance()
	subServiceImpl := services.SubServiceInit(bot)
	mainControllerImpl := controller.MainControllerInit()
	conn := config.ConnectToNatsBroker()
	natsBrokerImpl := config.NatsBrokerInit(conn, subServiceImpl)
	initialization := NewInitialization(bot, subServiceImpl, mainControllerImpl, natsBrokerImpl)
	return initialization
}

// wire.go:

var connectionsSet = wire.NewSet(config.GetBotInstance, config.ConnectToNatsBroker)

var natsBrokerSet = wire.NewSet(config.NatsBrokerInit, wire.Bind(new(config.NatsBroker), new(*config.NatsBrokerImpl)))

var serviceSet = wire.NewSet(services.SubServiceInit, wire.Bind(new(services.SubService), new(*services.SubServiceImpl)))

var controllersSet = wire.NewSet(controller.MainControllerInit, wire.Bind(new(controller.MainController), new(*controller.MainControllerImpl)))
